# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import db_pb2 as db__pb2


class dbhandleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AdIdToData = channel.unary_unary(
        '/dbhandle/AdIdToData',
        request_serializer=db__pb2.Id.SerializeToString,
        response_deserializer=db__pb2.AdData.FromString,
        )
    self.PostIdtoData = channel.unary_unary(
        '/dbhandle/PostIdtoData',
        request_serializer=db__pb2.Id.SerializeToString,
        response_deserializer=db__pb2.PostData.FromString,
        )
    self.UserIdtoData = channel.unary_unary(
        '/dbhandle/UserIdtoData',
        request_serializer=db__pb2.Id.SerializeToString,
        response_deserializer=db__pb2.UserData.FromString,
        )
    self.TagToPost = channel.unary_unary(
        '/dbhandle/TagToPost',
        request_serializer=db__pb2.Tag.SerializeToString,
        response_deserializer=db__pb2.Posts.FromString,
        )
    self.TagToAd = channel.unary_unary(
        '/dbhandle/TagToAd',
        request_serializer=db__pb2.Tag.SerializeToString,
        response_deserializer=db__pb2.Ads.FromString,
        )
    self.AuthorToPosts = channel.unary_unary(
        '/dbhandle/AuthorToPosts',
        request_serializer=db__pb2.Id.SerializeToString,
        response_deserializer=db__pb2.Posts.FromString,
        )
    self.AuthorToAd = channel.unary_unary(
        '/dbhandle/AuthorToAd',
        request_serializer=db__pb2.Id.SerializeToString,
        response_deserializer=db__pb2.Ads.FromString,
        )


class dbhandleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AdIdToData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PostIdtoData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserIdtoData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TagToPost(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TagToAd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthorToPosts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuthorToAd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_dbhandleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AdIdToData': grpc.unary_unary_rpc_method_handler(
          servicer.AdIdToData,
          request_deserializer=db__pb2.Id.FromString,
          response_serializer=db__pb2.AdData.SerializeToString,
      ),
      'PostIdtoData': grpc.unary_unary_rpc_method_handler(
          servicer.PostIdtoData,
          request_deserializer=db__pb2.Id.FromString,
          response_serializer=db__pb2.PostData.SerializeToString,
      ),
      'UserIdtoData': grpc.unary_unary_rpc_method_handler(
          servicer.UserIdtoData,
          request_deserializer=db__pb2.Id.FromString,
          response_serializer=db__pb2.UserData.SerializeToString,
      ),
      'TagToPost': grpc.unary_unary_rpc_method_handler(
          servicer.TagToPost,
          request_deserializer=db__pb2.Tag.FromString,
          response_serializer=db__pb2.Posts.SerializeToString,
      ),
      'TagToAd': grpc.unary_unary_rpc_method_handler(
          servicer.TagToAd,
          request_deserializer=db__pb2.Tag.FromString,
          response_serializer=db__pb2.Ads.SerializeToString,
      ),
      'AuthorToPosts': grpc.unary_unary_rpc_method_handler(
          servicer.AuthorToPosts,
          request_deserializer=db__pb2.Id.FromString,
          response_serializer=db__pb2.Posts.SerializeToString,
      ),
      'AuthorToAd': grpc.unary_unary_rpc_method_handler(
          servicer.AuthorToAd,
          request_deserializer=db__pb2.Id.FromString,
          response_serializer=db__pb2.Ads.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dbhandle', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
