# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SB.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SB.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x08SB.proto\"\x11\n\x03PId\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x0bPriorityIds\x12\x15\n\x03ids\x18\x01 \x03(\x0b\x32\x08.touples\"$\n\x07touples\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x32U\n\x0fSimilarityRecom\x12\x1f\n\x07\x41\x64Recom\x12\x04.PId\x1a\x0c.PriorityIds\"\x00\x12!\n\tPostRecom\x12\x04.PId\x1a\x0c.PriorityIds\"\x00\x62\x06proto3'
)




_PID = _descriptor.Descriptor(
  name='PId',
  full_name='PId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=29,
)


_PRIORITYIDS = _descriptor.Descriptor(
  name='PriorityIds',
  full_name='PriorityIds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='PriorityIds.ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=67,
)


_TOUPLES = _descriptor.Descriptor(
  name='touples',
  full_name='touples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='touples.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='touples.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=105,
)

_PRIORITYIDS.fields_by_name['ids'].message_type = _TOUPLES
DESCRIPTOR.message_types_by_name['PId'] = _PID
DESCRIPTOR.message_types_by_name['PriorityIds'] = _PRIORITYIDS
DESCRIPTOR.message_types_by_name['touples'] = _TOUPLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PId = _reflection.GeneratedProtocolMessageType('PId', (_message.Message,), {
  'DESCRIPTOR' : _PID,
  '__module__' : 'SB_pb2'
  # @@protoc_insertion_point(class_scope:PId)
  })
_sym_db.RegisterMessage(PId)

PriorityIds = _reflection.GeneratedProtocolMessageType('PriorityIds', (_message.Message,), {
  'DESCRIPTOR' : _PRIORITYIDS,
  '__module__' : 'SB_pb2'
  # @@protoc_insertion_point(class_scope:PriorityIds)
  })
_sym_db.RegisterMessage(PriorityIds)

touples = _reflection.GeneratedProtocolMessageType('touples', (_message.Message,), {
  'DESCRIPTOR' : _TOUPLES,
  '__module__' : 'SB_pb2'
  # @@protoc_insertion_point(class_scope:touples)
  })
_sym_db.RegisterMessage(touples)



_SIMILARITYRECOM = _descriptor.ServiceDescriptor(
  name='SimilarityRecom',
  full_name='SimilarityRecom',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='AdRecom',
    full_name='SimilarityRecom.AdRecom',
    index=0,
    containing_service=None,
    input_type=_PID,
    output_type=_PRIORITYIDS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PostRecom',
    full_name='SimilarityRecom.PostRecom',
    index=1,
    containing_service=None,
    input_type=_PID,
    output_type=_PRIORITYIDS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMILARITYRECOM)

DESCRIPTOR.services_by_name['SimilarityRecom'] = _SIMILARITYRECOM

# @@protoc_insertion_point(module_scope)
